### ISSUE TITLE
Missing 64 bit file

### ISSUE THREAD

**Issue by YungPhil** [jackaudio/jack-router#1]
Good afternoon -

 I have downloaded 64-bit installer: JACK 1.9.16 win64. 
Using Windows 7 Home Premium on a 64 bit Lenovo Laptop. 

I tried to register the 64 bit dll as per instructions on your website but the registration was rejected. 

On examining the'' Program Files (86)\Jack\ 64bits'' folder the dll file is missing.  Is this an error/omission in the download and would you be able to supply the relevant files. I want to use Jack with Hydrogen Drums and poss other DAW related progs .Hoping nyou can help - Thanks Phil

**Comment by falkTX** [comment]
jack router is not part of jack2 installer anymore. see https://jackaudio.org/news/2020/10/15/jack2-v1915-release-and-current-status.html

**Comment by YungPhil** [comment]
Thats interesting because the version I downloaded is 1.9.16 i.e. one on from 1.9.15 
I used the information from the Jack website as my guide to install on Windows 7 64bit https://jackaudio.org/faq/jack_on_windows.html

**Comment by falkTX** [comment]
Yeah sorry, that information is outdated.

**Comment by YungPhil** [comment]
Thanks - can you help on installing so that Hydrogen Drums 64bit will detect Jack - I downloaded and set up 1.9.16 - the System Inputs and Outputs are showing and sound is coming though jack.

**Comment by falkTX** [comment]
That is up to each developer/vendor to give support for JACK.
Might be Hydrogen simply has no JACK support on Windows, don't know, but you need to ask them, not here

**Comment by YungPhil** [comment]
Thanks - I have put in a request for info. They have a .dll file in 
their folder on the 64 bit version jack-0 but presumably not making the 
connection with jack



------ Original Message ------

**Comment by userdsp** [comment]
Can you give to us Jack2 last installer version where jack router is a part of him?

**Comment by userdsp** [comment]
Unfortunately, I do not have the knowledge to compile myself :/

**Comment by falkTX** [comment]
the binaries are in this repo, in the`binaries` dir

**Comment by userdsp** [comment]
Thanks it shows up!

**Comment by falkTX** [comment]
Since we have working jack-router binaries once again, and it is a separate project from JACK, I added it to the installer.
Test builds at https://github.com/jackaudio/jack2-releases/releases/tag/untagged-dc253c3f5ca380ada300

This is fully integrated with the installer. When checked, driver is registered automatically during install.
Uninstalling JACK will automatically uninstall the driver too.

Final release will be out on the 15th of January

and btw, I updated https://jackaudio.org/faq/jack_on_windows.html to reflect the changes.
feedback is very much appreciated.

I am closing this ticket since jack-router is available once again. just a few more days and the official stable release will have it.
